server:
  port: 8082
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  application:
    name: yupao-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  session:
    timeout: 86400
    storeType: redis
  redis:
    port: 6379
    host: localhost
    database: 1
dubbo:
  application:
    name: dubbo-springboot-user-consumer
    qos-port: 33333
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.139.1:8848?username=nacos&password=nacos&
    parameters.register-consumer-url: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: Knife4j
    description: "
    # aaa"
    email: xiaoymin@foxmail.com
    concat:
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: com.focus
        api-rule: package
        api-rule-resources:
          - com.example.project.controller