spring:
  application:
    name: user-center-backend
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testusercenter
    username: root
    password: 123456  #
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
server:
  port: 8081
  servlet:
    context-path: /api
dubbo:
  application:
    name: dubbo-springboot-user-consumer
    qos-port: 33333
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.3.14:8848?username=nacos&password=nacos&
    parameters.register-consumer-url: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    defaultEnumTypeHandler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      logic-delete-field: isDelete #
      logic-delete-value: 1
      logic-not-delete-value: 0
  typeEnumsPackage: com.acegear.cms.orm.enums
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
knife4j:
  enable: true
  openapi:
    title: Knife4j
    description: "
    # aaa"
    email: xiaoymin@foxmail.com
    concat:
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: com.focus
        api-rule: package
        api-rule-resources:
          - com.example.project.controller
